// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd4Sqk3pEQdDF2jDeWnAT0x_Vh1JDdwlc',
    appId: '1:964092543038:web:65629c8714db7542f4116f',
    messagingSenderId: '964092543038',
    projectId: 'nsic-chat-app',
    authDomain: 'nsic-chat-app.firebaseapp.com',
    storageBucket: 'nsic-chat-app.appspot.com',
    measurementId: 'G-RD25LE3416',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKT4QzJbjG_G6h-KpD8AfSO13inp6HcsM',
    appId: '1:964092543038:android:8d196c47ed49ec0cf4116f',
    messagingSenderId: '964092543038',
    projectId: 'nsic-chat-app',
    storageBucket: 'nsic-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJmmVG6o2BJ0BX0m5vCwLuq2p4dBq5sKM',
    appId: '1:964092543038:ios:ae583554abcb7ab8f4116f',
    messagingSenderId: '964092543038',
    projectId: 'nsic-chat-app',
    storageBucket: 'nsic-chat-app.appspot.com',
    iosClientId: '964092543038-r3utr45ochl41qfau18mhfvg85obk577.apps.googleusercontent.com',
    iosBundleId: 'com.arunbalaji.signalChat',
  );
}
